-- Card identity must be the logical (note_guid, ord) pair, not card_id.
--
-- card_id is a local Anki creation timestamp: the SAME logical card (the card
-- generated by template `ord` of note `note_guid`) has a DIFFERENT card_id in
-- every collection that generated it. Keying cards by card_id therefore let two
-- devices (e.g. Anki desktop and Kelma mobile) push two separate server rows
-- for one logical card, inflating deck counts and breaking scheduling sync.
--
-- This migration:
--   1. de-duplicates existing rows, keeping the most recently modified per
--      (user_id, note_guid, ord),
--   2. replaces the UNIQUE(user_id, card_id) constraint with
--      UNIQUE(user_id, note_guid, ord).
-- card_id remains as an attribute (the canonical/first-writer id) so clients
-- can still address and pull cards by id.

-- 1. De-duplicate: keep the newest modified_at row in each logical group.
DELETE FROM cards c
USING cards d
WHERE c.user_id = d.user_id
  AND c.note_guid = d.note_guid
  AND c.ord = d.ord
  AND c.note_guid <> ''
  AND (
        c.modified_at < d.modified_at
        OR (c.modified_at = d.modified_at AND c.id < d.id)
      );

-- 2. Swap the uniqueness constraint. The logical index is partial: blank note
-- GUIDs are not valid sync identities (clients skip them), so they are excluded
-- rather than colliding on (user_id, '', ord).
ALTER TABLE cards DROP CONSTRAINT IF EXISTS cards_user_id_card_id_key;
CREATE UNIQUE INDEX IF NOT EXISTS idx_cards_logical
    ON cards (user_id, note_guid, ord)
    WHERE note_guid <> '';
